services:
  - type: web
    name: myapp
    env: node
    plan: free
    envVars:
      - key: NPM_FLAGS
        value: '--prefix ./client'
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: false
    region: virginia
    numInstances: 1

databases:
  - name: mydb
    plan: free
