services:
  - type: web
    name: myapp
    env: node
    repo: https://github.com/nunera/Ultraviolet-App.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
